### ISSUE TITLE
Add support for Artifactory Projects

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/artifactory-resource#115]
https://jfrog.com/help/r/jfrog-rest-apis/build-upload

> The `?project=<project>` parameter applies to the Projects feature and is optional.

The `project` query parameter is also supported when retrieving builds:

```
GET /api/build/my-build?project='projectKey'
```

It doesn't appear to be supported when querying builds using AQL. It remains to be seen how much of a problem that will be.

**Comment by kvmw** [comment]
@wilkinsona  Using `get` with `save_build_info: true` param is failing. 
As you've mentioned above looks like GET also supports `project` as query parameter which apparently artifactory-resource has not implemented it yet. 
So a get like the following:
```yaml
  - get: artifactory
    passed: [ stage ]
    params:
      save_build_info: true
```
Is failing with the following exception:
```java
2024-02-13T10:00:14.703Z DEBUG 14 --- [           main] i.s.c.a.command.InHandler                : Using artifactory server https://<SERVER>/artifactory
2024-02-13T10:00:18.569Z DEBUG 14 --- [           main] i.s.c.a.a.HttpArtifactoryBuildRuns       : Getting deployed artifacts for <BUILD-NUMBER>
2024-02-13T10:00:18.571Z DEBUG 14 --- [           main] i.s.c.a.a.HttpArtifactoryBuildRuns       : Searching with AQL items.find({"@build.name" : "<BULD-NAME>", "@build.number" : "<BUILD-NUMBER>"})
Downloading build <BUILD-NUMBER> from https://<SERVER>/artifactory using 1 thread(s)
Downloading <ARTIFACT>.jar from <REPO>
Downloading <ARTIFACT>.jar.asc from <REPO>
Downloading <ARTIFACT>.pom from <REPO>
Downloading <ARTIFACT>.pom.asc from <REPO>
2024-02-13T10:00:22.901Z DEBUG 14 --- [           main] i.s.c.a.command.InHandler                : Generating maven metadata
2024-02-13T10:00:22.925Z DEBUG 14 --- [           main] i.s.c.a.a.HttpArtifactoryBuildRuns       : Getting raw build info for <BUILD-NUMBER>
2024-02-13T10:00:23.214Z  INFO 14 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-02-13T10:00:23.256Z ERROR 14 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.web.client.HttpClientErrorException$NotFound: 404 : "{<EOL>  "errors" : [ {<EOL>    "status" : 404,<EOL>    "message" : "No build was found for build name: <BUILD-NAME>, build number: <BUILD-NUMBER> "<EOL>  } ]<EOL>}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:112)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:932)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:881)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:821)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:413)
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryBuildRuns.getRawBuildInfo(HttpArtifactoryBuildRuns.java:129)
	at io.spring.concourse.artifactoryresource.command.InHandler.handle(InHandler.java:93)
	at io.spring.concourse.artifactoryresource.command.InCommand.run(InCommand.java:58)
	at io.spring.concourse.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:59)
```

Removing the `save_build_info: true` fixes the error but without build-info it is not possible to promote the builds.

**Comment by wilkinsona** [comment]
I'm not sure that I see the connection to this issue as it's not clear if you're using Artifactory's project feature. I guess that you are? Note that support for projects has been implemented, just not yet released. You could try `0.0.19-SNAPSHOT` and see if it meets your needs. If it doesn't, we'll need some more information about your situation to be able to make any progress.

**Comment by kvmw** [comment]
Yes, I am using the Artifactory's project feature in `0.0.19-SNAPSHOT` to upload my artifacts as well as build-info.  the `put`  step is successful and i can verify all the artifacts and also the build-info are in the correct repo. but trying to `get` the same resource, after `put`, is failing.  

My understanding is that this feature (support for `project`) has been implemented for `out` (put) but not for `in` (get) in artifactory-resource.

**Comment by kvmw** [comment]
I could `curl` the [build-info](https://jfrog.com/help/r/jfrog-rest-apis/build-info) endpoint, successfully, with `project` as query parameter. 
```
curl  -u "<username>:<token>" "<server>/api/build/<build-name>/<build-number>?project=<project-name>"
```

The `project` query parameter should be added into [HttpArtifactoryBuildRuns::getRawBuildInfo](https://github.com/spring-io/artifactory-resource/blob/main/src/main/java/io/spring/concourse/artifactoryresource/artifactory/HttpArtifactoryBuildRuns.java#L125-L127), if `project` is not null.  Exactly like what has been done in [HttpArtifactoryBuildRuns::add](https://github.com/spring-io/artifactory-resource/blob/main/src/main/java/io/spring/concourse/artifactoryresource/artifactory/HttpArtifactoryBuildRuns.java#L96-L99).
