### ISSUE TITLE
Concourse 3.9.X breaks the resource

### ISSUE THREAD

**Issue by louisthomas** [spring-io/artifactory-resource#12]
Due to a bug in Concourse 3.9 the resource fails with. [See here](https://github.com/concourse/concourse/issues/2042)

```
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964) ~[na:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1921) ~[na:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1904) ~[na:1.8.0_162]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420) ~[na:1.8.0_162]
```

**Comment by philwebb** [comment]
Closing in favor of PR ##12
