### ISSUE TITLE
JSON parse error: Cannot deserialize value of type java.time.Instant

### ISSUE THREAD

**Issue by Skyr** [spring-io/artifactory-resource#125]
Version of artifactory-resource in use: 0.0.19 (same exception with 0.0.18; works with 0.0.16).
Artifactory version: 7.49.10

In the get step, I run into the following stacktrace:

```
org.springframework.web.client.RestClientException: Error while extracting response for type [class io.spring.concourse.artifactoryresource.artifactory.payload.DeployedArtifactsSearchQueryResponse] and content type [application/json]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:118)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1149)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1132)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:882)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:721)
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryBuildRuns.search(HttpArtifactoryBuildRuns.java:149)
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryBuildRuns.getDeployedArtifacts(HttpArtifactoryBuildRuns.java:142)
	at io.spring.concourse.artifactoryresource.command.InHandler.handle(InHandler.java:82)
	at io.spring.concourse.artifactoryresource.command.InCommand.run(InCommand.java:58)
	at io.spring.concourse.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:59)
	at org.springframework.boot.SpringApplication.lambda$callRunner$4(SpringApplication.java:786)
	at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83)
	at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60)
	at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:774)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:341)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at io.spring.concourse.artifactoryresource.Application.main(Application.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize value of type `java.time.Instant` from String "2024-05-15T13:49:23.009+02:00": Failed to deserialize java.time.Instant: (java.time.format.DateTimeParseException) Text '2024-05-15T13:49:23.009+02:00' could not be parsed, unparsed text found at index 26
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:406)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:354)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:103)
	... 36 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.Instant` from String "2024-05-15T13:49:23.009+02:00": Failed to deserialize java.time.Instant: (java.time.format.DateTimeParseException) Text '2024-05-15T13:49:23.009+02:00' could not be parsed, unparsed text found at index 26
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 9, column: 15] (through reference chain: io.spring.concourse.artifactoryresource.artifactory.payload.DeployedArtifactsSearchQueryResponse["results"]->java.util.ArrayList[0]->io.spring.concourse.artifactoryresource.artifactory.payload.DeployedArtifact["created"])
	at (...)
```

Probably an issue with the usage of `Instant` which is not timezone-aware.

**Comment by wilkinsona** [comment]
I think this was broken in https://github.com/spring-io/artifactory-resource/commit/06fcf11793387016a102c6cd1520d4f809adbc2e where we switched from:

`@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXX")`

to:

`@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSX", timezone = "UTC")`

This works fine for https://repo.spring.io which returns json like this:

```
    "path": "plugins-release-local/io/spring/dependency-management/io.spring.dependency-management.gradle.plugin/1.1.5/io.spring.dependency-management.gradle.plugin-1.1.5.pom.asc",
    "type": "file",
    "size": 833,
    "created": "2024-05-03T11:24:02.895Z",
    "modified": "2024-05-03T11:24:02.739Z",
    "sha1": "58e3800e8c3d43cdb2e9b513333b252de8627e05",
    "sha256": "d40cd37bd284f9f2229b7a8c3c530d110b03970b3fb9f9555d292fef987b8cf5",
    "md5": "a2c71ce2b5ad71caf045048b37eb3f9c",
    "props": {
      "build.name": [
        "dependency-management-plugin-1.1.5"
      ],
      "build.number": [
        "3"
      ],
      "build.timestamp": [
        "1714735440074"
      ]
    }
```

I guess there's a setting somewhere in Artifactory that affects the exact format of the timestamps that it returns. 

[artifactory-client-java](https://github.com/jfrog/artifactory-client-java) from JFrog [uses](https://github.com/jfrog/artifactory-client-java/blob/e39db33c2d8b87134bac115ae43a1408ee1964b6/api/src/main/java/org/jfrog/artifactory/client/model/AqlItem.java#L15) `yyyy-MM-dd'T'HH:mm:ss.SSSXXX` so I guess we should align with that. It can parse both `2024-05-15T13:49:23.009+02:00` and `2024-05-03T11:24:02.739Z` so it should meet our needs.

**Comment by philwebb** [comment]
We are not planning any further updates to this project and as such are closing all issues.
