### ISSUE TITLE
Is the artifactory-resource still valid or deprecated?

### ISSUE THREAD

**Issue by akoranne** [spring-io/artifactory-resource#16]
When I try to use the `springio/artifactory-resource`, I get following errors...

```
2018-07-19 18:39:32.977 ERROR 14 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:726) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:713) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
```

I followed the outlined instructions in my pipeline. 

Is this resource still valid or is it deprecated in favor of another? If it is deprecated, can you please let me know, what that is?

If you want, you can ping me on oss-cloud-foundry slack.

Thanks,
--ajay

**Comment by philwebb** [comment]
@akoranne The resource is still valid and we use it in [Spring Boot](https://github.com/spring-projects/spring-boot/blob/master/ci/pipeline.yml#L5). Are you still having the problem? Are you able to share a small project that replicates it?

**Comment by akoranne** [comment]
@philwebb,

My sample project is - https://github.com/akoranne/test-artifactory-resource
The `pipeline-springio-resource.yml` is using the 'springio/artifactory-resource'. And I was able to recreate the error, I mentioned above. 

Please let me know, if you have any questions. 
Thank you for your help!

**Comment by philwebb** [comment]
The full stacktrace is:

```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	
	at io.spring.concourse.artifactoryresource.Application.main(Application.java:40) [classes!/:0.0.5-SNAPSHOT]
	
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [artifactory-resource.jar:0.0.5-SNAPSHOT]
	
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [artifactory-resource.jar:0.0.5-SNAPSHOT]
	
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [artifactory-resource.jar:0.0.5-SNAPSHOT]
	
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [artifactory-resource.jar:0.0.5-SNAPSHOT]
	
Caused by: java.lang.IllegalStateException: File '/tmp/build/put/springio-res' does not exist
	
	at org.springframework.util.Assert.state(Assert.java:73) ~[spring-core-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	
	at io.spring.concourse.artifactoryresource.io.Directory.<init>(Directory.java:44) ~[classes!/:0.0.5-SNAPSHOT]
	
	at io.spring.concourse.artifactoryresource.io.Directory.getSubDirectory(Directory.java:76) ~[classes!/:0.0.5-SNAPSHOT]
	
	at io.spring.concourse.artifactoryresource.command.OutHandler.getDeployableArtifacts(OutHandler.java:130) ~[classes!/:0.0.5-SNAPSHOT]
	
	at io.spring.concourse.artifactoryresource.command.OutHandler.handle(OutHandler.java:102) ~[classes!/:0.0.5-SNAPSHOT]
	
	at io.spring.concourse.artifactoryresource.command.OutCommand.run(OutCommand.java:54) ~[classes!/:0.0.5-SNAPSHOT]
	
	at io.spring.concourse.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:52) ~[classes!/:0.0.5-SNAPSHOT]
	
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	
	... 13 common frames omitted
```

**Comment by philwebb** [comment]
@akoranne There were a few issues in your pipeline definition. I've sent you a [pull request](https://github.com/akoranne/test-artifactory-resource/pull/1) to fix them.
