### ISSUE TITLE
Provide a Way to Set JAVA_OPTS

### ISSUE THREAD

**Issue by nebhale** [spring-io/artifactory-resource#18]
Currently I'm experiencing an issue when using the resource to `put` a ~200M file.  When the JVM runs, a failure occurs with the following stack trace:

```plain

Deploying 1 artifacts to https://repo.spring.io as build 2
Deploying /org/cloudfoundry/openjdk/org.cloudfoundry.openjdk/1.0.0-BUILD-SNAPSHOT/org.cloudfoundry.openjdk-1.0.0-BUILD-SNAPSHOT.tgz {build.name=OpenJDK Buildpack, build.number=2} (1d4298f61c7f0828c5fec660defba3e3e2c2d889/31998c5792b7b22e198e3299e2500e95)
2018-09-21 19:40:08.638 ERROR 15 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236) ~[na:1.8.0_151]
	at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191) ~[na:1.8.0_151]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:44) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:99) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.http.client.support.BasicAuthorizationInterceptor.intercept(BasicAuthorizationInterceptor.java:63) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:86) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:70) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:590) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryRepository.deployUsingContent(HttpArtifactoryRepository.java:102) ~[classes!/:0.0.4]
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryRepository.deploy(HttpArtifactoryRepository.java:84) ~[classes!/:0.0.4]
	at io.spring.concourse.artifactoryresource.command.OutHandler.deployArtifacts(OutHandler.java:192) ~[classes!/:0.0.4]
	at io.spring.concourse.artifactoryresource.command.OutHandler.handle(OutHandler.java:99) ~[classes!/:0.0.4]
	at io.spring.concourse.artifactoryresource.command.OutCommand.run(OutCommand.java:54) ~[classes!/:0.0.4]
	at io.spring.concourse.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:52) ~[classes!/:0.0.4]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:723) ~[spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:713) ~[spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) ~[spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) ~[spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) ~[spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) ~[spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at io.spring.concourse.artifactoryresource.Application.main(Application.java:40) ~[classes!/:0.0.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[artifactory-resource.jar:0.0.4]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[artifactory-resource.jar:0.0.4]
```

It seems to indicate that while reading in the file it exhausts the JVM's allocated heap space.  There's certainly a question as to whether the entire file should be loaded into memory (and then copied!), but assuming that it stays that way, the solution to this problem is to adjust the amount of heap available to the JVM.  However, there is [no way](https://github.com/spring-io/artifactory-resource/blob/master/assets/out#L4) to add these values.

I'd like some way to modify the heap size (but a more general solution might be warranted depending on your investigation) of the JVM when it runs.

**Comment by philwebb** [comment]
Created #27 to fix the memory issue.

**Comment by philwebb** [comment]
There's not a great way to do this unfortunately. We'll need to somehow pass the options in before we start the java process. We could probably use `jq` to parse the JSON and pick out the `JAVA_OPTS` but it will make the launch script a bit more involved.

Given that I think the memory issue is now fixed, I'm tempted to hold off before trying to fix this one.

@nebhale Other than memory, is there another reason for you wanting to set `JAVA_OPTS`?

**Comment by nebhale** [comment]
Yep you're good to go.
