### ISSUE TITLE
strip_snapshot_timestamps causing StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jvalkeal** [spring-io/artifactory-resource#5]
Structure what resource is trying to push looks like:
```
org/springframework/cloud/skipper/acceptance/app/skipper-server-with-drivers
org/springframework/cloud/skipper/acceptance/app/skipper-server-with-drivers/maven-metadata-local.xml
org/springframework/cloud/skipper/acceptance/app/skipper-server-with-drivers/1.0.0.SNAPSHOT
org/springframework/cloud/skipper/acceptance/app/skipper-server-with-drivers/1.0.0.SNAPSHOT/maven-metadata-local.xml
org/springframework/cloud/skipper/acceptance/app/skipper-server-with-drivers/1.0.0.SNAPSHOT/skipper-server-with-drivers-1.0.0.SNAPSHOT.pom
org/springframework/cloud/skipper/acceptance/app/skipper-server-with-drivers/1.0.0.SNAPSHOT/skipper-server-with-drivers-1.0.0.SNAPSHOT.jar
```
I had to add `strip_snapshot_timestamps: false` as otherwise push failed with:
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[na:1.8.0_131]
	at io.spring.concourse.artifactoryresource.maven.MavenCoordinates.fromPath(MavenCoordinates.java:144) ~[classes!/:0.0.3]
	at io.spring.concourse.artifactoryresource.command.OutHandler.stripSnapshotTimestamp(OutHandler.java:172) ~[classes!/:0.0.3]
	at io.spring.concourse.artifactoryresource.command.OutHandler.lambda$getDeployableArtifacts$0(OutHandler.java:134) ~[classes!/:0.0.3]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_131]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_131]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_131]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_131]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_131]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_131]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_131]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_131]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_131]
	at io.spring.concourse.artifactoryresource.command.OutHandler.getDeployableArtifacts(OutHandler.java:137) ~[classes!/:0.0.3]
```
We should handle this error as it was difficult to track down.

**Comment by philwebb** [comment]
The root cause of the error was that we didn't filter the `maven-metadata-local.xml` file. I've fixed that and also improved the exception messages in `MavenCoordinates` parsing.
