### ISSUE TITLE
Out of memory issues when transfering content

### ISSUE THREAD

**Issue by philwebb** [spring-io/artifactory-resource#50]
It appears that #27 has re-appeared somehow.

**Comment by philwebb** [comment]
```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236) ~[na:1.8.0_192]
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118) ~[na:1.8.0_192]
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93) ~[na:1.8.0_192]
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153) ~[na:1.8.0_192]
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:143) ~[spring-core-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.http.converter.ResourceHttpMessageConverter.writeContent(ResourceHttpMessageConverter.java:132) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:124) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:45) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate$HttpEntityRequestCallback.doWithRequest(RestTemplate.java:948) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:733) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:637) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryRepository.deployUsingContent(HttpArtifactoryRepository.java:103) ~[classes!/:0.0.8]
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryRepository.deploy(HttpArtifactoryRepository.java:85) ~[classes!/:0.0.8]
	at io.spring.concourse.artifactoryresource.command.OutHandler.deployArtifacts(OutHandler.java:201) ~[classes!/:0.0.8]
	at io.spring.concourse.artifactoryresource.command.OutHandler.handle(OutHandler.java:108) ~[classes!/:0.0.8]
	at io.spring.concourse.artifactoryresource.command.OutCommand.run(OutCommand.java:54) ~[classes!/:0.0.8]
	at io.spring.concourse.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:52) ~[classes!/:0.0.8]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at io.spring.concourse.artifactoryresource.Application.main(Application.java:40) [classes!/:0.0.8]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [artifactory-resource.jar:0.0.8]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [artifactory-resource.jar:0.0.8]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [artifactory-resource.jar:0.0.8]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [artifactory-resource.jar:0.0.8]
```

**Comment by philwebb** [comment]
The error is similar to #27 but not exactly the same. AFAICT the same issue exists in earlier versions so I'm not sure why the limit has suddenly been reached.
