### ISSUE TITLE
HttpArtifactoryRepository swallows exceptions

### ISSUE THREAD

**Issue by philwebb** [spring-io/artifactory-resource#51]
The `HttpArtifactoryRepository` class can currently swallow HTTP exceptions when trying to use a checksum deploy.

**Comment by philwebb** [comment]
Despite setting the length the checksum upload still fails with

```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at io.spring.concourse.artifactoryresource.Application.main(Application.java:40) [classes!/:0.0.10-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [artifactory-resource.jar:0.0.10-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [artifactory-resource.jar:0.0.10-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [artifactory-resource.jar:0.0.10-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [artifactory-resource.jar:0.0.10-SNAPSHOT]
Caused by: org.springframework.web.client.HttpClientErrorException: 411 Length Required
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:101) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:637) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryRepository.deployUsingChecksum(HttpArtifactoryRepository.java:98) ~[classes!/:0.0.10-SNAPSHOT]
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryRepository.deploy(HttpArtifactoryRepository.java:81) ~[classes!/:0.0.10-SNAPSHOT]
	at io.spring.concourse.artifactoryresource.command.OutHandler.deployArtifacts(OutHandler.java:201) ~[classes!/:0.0.10-SNAPSHOT]
	at io.spring.concourse.artifactoryresource.command.OutHandler.handle(OutHandler.java:108) ~[classes!/:0.0.10-SNAPSHOT]
	at io.spring.concourse.artifactoryresource.command.OutCommand.run(OutCommand.java:54) ~[classes!/:0.0.10-SNAPSHOT]
	at io.spring.concourse.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:52) ~[classes!/:0.0.10-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	... 13 common frames omitted
```
