### ISSUE TITLE
Implicit GET 404

### ISSUE THREAD

**Issue by akath19** [spring-io/artifactory-resource#53]
Hi,

I just started using this resource to upload to a private artifactory, everything seems to work correctly except that the implicit GET run by Concourse after out is returning 404 on all artifact uploads, however, the artifacts are showing correctly in our artifactory and can be downloaded without issue, here's the stack trace I'm seeing:

```
2019-05-09 15:13:29.882 ERROR 14 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at io.spring.concourse.artifactoryresource.Application.main(Application.java:40) [classes!/:0.0.10]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [artifactory-resource.jar:0.0.10]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [artifactory-resource.jar:0.0.10]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [artifactory-resource.jar:0.0.10]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [artifactory-resource.jar:0.0.10]
Caused by: org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:85) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:637) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryBuildRuns.getDeployedArtifacts(HttpArtifactoryBuildRuns.java:104) ~[classes!/:0.0.10]
	at io.spring.concourse.artifactoryresource.command.InHandler.handle(InHandler.java:78) ~[classes!/:0.0.10]
	at io.spring.concourse.artifactoryresource.command.InCommand.run(InCommand.java:54) ~[classes!/:0.0.10]
	at io.spring.concourse.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:52) ~[classes!/:0.0.10]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	... 13 common frames omitted
```

Here's a screenshot of the build process that shows the artifact was uploaded correctly:
![Screen Shot 2019-05-09 at 10 20 04 AM](https://user-images.githubusercontent.com/3260715/57465365-152b1b80-7244-11e9-88c6-992f69047247.png)

Is there any way to disable this behaviour?, it's breaking a correct pipeline run and I didn't see any similar issue in any issues so far

EDIT: I just noticed that the Artifactory version we have installed is really old (3.2.2), maybe that's the reason this is failing...

**Comment by philwebb** [comment]
That specific REST query is [in this method](https://github.com/spring-io/artifactory-resource/blob/db7d100cd97ce6512857f9ec1d01812b7d362b44/src/main/java/io/spring/concourse/artifactoryresource/artifactory/HttpArtifactoryBuildRuns.java#L97). It calls `/api/search/aql`.

It looks like support for build items wasn't added until [Artifactory 4.2.0](https://www.jfrog.com/confluence/display/RTF/Artifactory+Query+Language).

**Comment by philwebb** [comment]
There might be another way to obtain that information. I chose AQL because it works in both the pro and oss version. I'm not sure we can realistically support 3.x versions of Artifactory. We certainly can't test them easily.

@akath19 Are you able to upgrade your server to a more recent version?

**Comment by akath19** [comment]
Yeah, I already started the internal process for that, hopefully it'll be updated to the latest version

Don't worry about supporting old versions, I fully understand that it's a pain.

I'm closing this cause it's not an issue with the resource.
