### ISSUE TITLE
Cannot push non-maven artifacts without setting strip_snapshot_timestamps to false

### ISSUE THREAD

**Issue by atzawada** [spring-io/artifactory-resource#55]
Hello,
I am trying to push a Vue.js project to Artifactory using this resource. Here is my source configuration:
```yaml
- name: artifactory
  type: artifactory-resource
  source:
    uri: REMOVED
    build_name: ((build-name))
    username: ((pcf-user-password-secrets.username))
    password: ((pcf-user-password-secrets.password))
```
I have bundled the build project as a .tgz file and attempt to push it as such. Here is my put step configuration:
```yaml
- put: artifactory
    params:
      debug: true
      folder: push-to-artifactory
      repo: npm-local
      module_layout: none
      artifact_set:
      - include:
            - "XXXX/XXXX-web-app/*.tgz"
```
The push failed with the following stacktrace:
```
Caused by: java.lang.IllegalStateException: Unable to parse maven coordinates from path 'XXXX/XXXX-web-app/XXXX-web-app-0.0.6.tgz'
	at io.spring.concourse.artifactoryresource.maven.MavenCoordinates.fromPath(MavenCoordinates.java:155) ~[classes!/:0.0.10]
	at io.spring.concourse.artifactoryresource.command.OutHandler.stripSnapshotTimestamp(OutHandler.java:181) ~[classes!/:0.0.10]
	at io.spring.concourse.artifactoryresource.command.OutHandler.lambda$getDeployableArtifacts$0(OutHandler.java:143) ~[classes!/:0.0.10]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_192]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_192]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_192]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_192]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_192]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_192]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_192]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_192]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_192]
	at io.spring.concourse.artifactoryresource.command.OutHandler.getDeployableArtifacts(OutHandler.java:146) ~[classes!/:0.0.10]
	at io.spring.concourse.artifactoryresource.command.OutHandler.handle(OutHandler.java:103) ~[classes!/:0.0.10]
	at io.spring.concourse.artifactoryresource.command.OutCommand.run(OutCommand.java:54) ~[classes!/:0.0.10]
	at io.spring.concourse.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:52) ~[classes!/:0.0.10]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	... 13 common frames omitted
Caused by: java.lang.IllegalStateException: Path does not match folder pattern
	at org.springframework.util.Assert.state(Assert.java:73) ~[spring-core-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at io.spring.concourse.artifactoryresource.maven.MavenCoordinates.fromPath(MavenCoordinates.java:118) ~[classes!/:0.0.10]
	... 29 common frames omitted
```
The resource still appears to be looking for a maven-based directory structure for the push to Artifactory. Is there something I am missing? Thanks

**Comment by wilkinsona** [comment]
What happens if you add `strip_snapshot_timestamps: false` to the `params` for the put?

**Comment by atzawada** [comment]
That works, thanks @wilkinsona ! I am able to push successfully.

**Comment by wilkinsona** [comment]
Thanks for letting us know. I'm going to re-open this as I wonder if we can be a bit smarter here when the `module_layout` is set to `none`.
