### ISSUE TITLE
artifact_set properties required

### ISSUE THREAD

**Issue by jvalkeal** [spring-io/artifactory-resource#6]
I originally had something like:
```
      artifact_set:
      - include:
        - "**/*.jar"
```

This caused:
```
Caused by: java.lang.NullPointerException: null
	at java.util.HashMap.putMapEntries(HashMap.java:500) ~[na:1.8.0_131]
	at java.util.HashMap.putAll(HashMap.java:784) ~[na:1.8.0_131]
	at io.spring.concourse.artifactoryresource.command.OutHandler.addArtifactSetProperties(OutHandler.java:154) ~[classes!/:0.0.3]
	at io.spring.concourse.artifactoryresource.command.OutHandler.getDeployableArtifactProperties(OutHandler.java:143) ~[classes!/:0.0.3]
	at io.spring.concourse.artifactoryresource.command.OutHandler.lambda$getDeployableArtifacts$0(OutHandler.java:131) ~[classes!/:0.0.3]
```

As a workaround I had to add dummy property:

```
      artifact_set:
      - include:
        - "**/*.jar"
        properties:
          dummy: value
```

**Comment by jvalkeal** [comment]
Maybe this is not that important as it looks like `artifact_set` is just for setting properties (mistake I made in #7) so it's anyway required. Thought it'd be nice to get some sort of proper error message instead of NPE.

**Comment by philwebb** [comment]
This was a bug in the `ArtifactSet`, it should have converted `null` "properties" to and empty collection.
