### ISSUE TITLE
Show stack traces only in debug mode

### ISSUE THREAD

**Issue by gabipetrovay** [spring-io/artifactory-resource#67]
The user of the artifactory resource should not care that the implementation is Java and is not interested in the stack traces thrown by the java code.

They could be made visible when `debug: true` is provided. Otherwise the exception message should be enough.

This helps:
* the Concourse user focus more on the real errors
* the implementers of this resource type to provide better errors (and not rely on the nested exceptions:

```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:778) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at io.spring.concourse.artifactoryresource.Application.main(Application.java:40) [classes!/:0.0.13-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [artifactory-resource.jar:0.0.13-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [artifactory-resource.jar:0.0.13-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [artifactory-resource.jar:0.0.13-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [artifactory-resource.jar:0.0.13-SNAPSHOT]
Caused by: java.lang.IllegalStateException: Unable to parse maven coordinates from path 'ibis-common-amqp/target/ibis-common-amqp-3.8.3-SNAPSHOT.jar'
	at io.spring.concourse.artifactoryresource.maven.MavenCoordinates.fromPath(MavenCoordinates.java:146) ~[classes!/:0.0.13-SNAPSHOT]
	at io.spring.concourse.artifactoryresource.command.OutHandler.stripSnapshotTimestamp(OutHandler.java:192) ~[classes!/:0.0.13-SNAPSHOT]
	at io.spring.concourse.artifactoryresource.command.OutHandler.lambda$getBatchedArtifacts$0(OutHandler.java:153) ~[classes!/:0.0.13-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_192]
	at io.spring.concourse.artifactoryresource.command.OutHandler.lambda$getBatchedArtifacts$1(OutHandler.java:147) ~[classes!/:0.0.13-SNAPSHOT]
	at java.util.Map.forEach(Map.java:630) ~[na:1.8.0_192]
	at io.spring.concourse.artifactoryresource.command.OutHandler.getBatchedArtifacts(OutHandler.java:146) ~[classes!/:0.0.13-SNAPSHOT]
	at io.spring.concourse.artifactoryresource.command.OutHandler.handle(OutHandler.java:113) ~[classes!/:0.0.13-SNAPSHOT]
	at io.spring.concourse.artifactoryresource.command.OutCommand.run(OutCommand.java:53) ~[classes!/:0.0.13-SNAPSHOT]
	at io.spring.concourse.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:50) ~[classes!/:0.0.13-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	... 13 common frames omitted
Caused by: java.lang.IllegalStateException: Path does not match folder pattern
	at org.springframework.util.Assert.state(Assert.java:73) ~[spring-core-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at io.spring.concourse.artifactoryresource.maven.MavenCoordinates.fromPath(MavenCoordinates.java:114) ~[classes!/:0.0.13-SNAPSHOT]
	... 23 common frames omitted
```

**Comment by philwebb** [comment]
It would be nice if user-facing exceptions (like your example) could be presented with less noise. So far we've preferred the full stacktrace just because it's much simpler for us to code and the information is generally useful if there's an actual bug we need to fix.

**Comment by philwebb** [comment]
I think we're going to need to leave the stacktraces for now. It's going to be quite a bit of work to find and change all the user-facing errors and I'm worried we'll end up hiding something useful.
