### ISSUE TITLE
Deploying a single jar: IllegalStateException: Path does not match folder pattern

### ISSUE THREAD

**Issue by ringods** [spring-io/artifactory-resource#79]
I am experimenting with this version of the `artifactory-resource`. To test, I forked the following two repositories which explain publishing Maven artifacts:

* https://github.com/MarcialRosales/maven-concourse-pipeline
* https://github.com/MarcialRosales/maven-concourse-pipeline-app1

Forks are here: https://github.com/ringods

The pipeline is on this branch: https://github.com/ringods/maven-concourse-pipeline/tree/05_deploy_and_verify

When running this setup, I get this error on `put: build-artifact-resource`:

```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.4.0.jar!/:2.4.0]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785) [spring-boot-2.4.0.jar!/:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) [spring-boot-2.4.0.jar!/:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) [spring-boot-2.4.0.jar!/:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) [spring-boot-2.4.0.jar!/:2.4.0]
	at io.spring.concourse.artifactoryresource.Application.main(Application.java:40) [classes!/:0.0.13]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [artifactory-resource.jar:0.0.13]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [artifactory-resource.jar:0.0.13]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [artifactory-resource.jar:0.0.13]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [artifactory-resource.jar:0.0.13]
Caused by: java.lang.IllegalStateException: Unable to parse maven coordinates from path 'maven-concourse-pipeline-app1-1.0.0-rc.8+cc67b35a6b8c50eab59b069b10490517f4e85fdd.jar'
	at io.spring.concourse.artifactoryresource.maven.MavenCoordinates.fromPath(MavenCoordinates.java:146) ~[classes!/:0.0.13]
	at io.spring.concourse.artifactoryresource.command.OutHandler.stripSnapshotTimestamp(OutHandler.java:212) ~[classes!/:0.0.13]
	at io.spring.concourse.artifactoryresource.command.OutHandler.lambda$null$0(OutHandler.java:171) ~[classes!/:0.0.13]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_192]
	at io.spring.concourse.artifactoryresource.command.OutHandler.lambda$getBatchedArtifacts$1(OutHandler.java:165) ~[classes!/:0.0.13]
	at java.util.Map.forEach(Map.java:630) ~[na:1.8.0_192]
	at io.spring.concourse.artifactoryresource.command.OutHandler.getBatchedArtifacts(OutHandler.java:164) ~[classes!/:0.0.13]
	at io.spring.concourse.artifactoryresource.command.OutHandler.handle(OutHandler.java:121) ~[classes!/:0.0.13]
	at io.spring.concourse.artifactoryresource.command.OutCommand.run(OutCommand.java:53) ~[classes!/:0.0.13]
	at io.spring.concourse.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:50) ~[classes!/:0.0.13]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.4.0.jar!/:2.4.0]
	... 13 common frames omitted
Caused by: java.lang.IllegalStateException: Path does not match folder pattern
	at org.springframework.util.Assert.state(Assert.java:76) ~[spring-core-5.3.1.jar!/:5.3.1]
	at io.spring.concourse.artifactoryresource.maven.MavenCoordinates.fromPath(MavenCoordinates.java:114) ~[classes!/:0.0.13]
	... 23 common frames omitted
```

This looks like #55 with the big difference that in this case it *is* a Maven artifact.

What am I doing wrong?

**Comment by wilkinsona** [comment]
The artifacts that you are trying to deploy should be in a directory structure that matches a Maven repository.  In your case, the artifacts belong to a single module and they should all be in `com/example/maven-concourse-pipeline-app1/0.0.1-SNAPSHOT`. Typically, when building with Maven you'd use the Deploy plugin's [deploy goal](https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html) and `altDeploymentRepository` to deploy to the local file system. You'd then pass the `altDeploymentRepository` location as an input to this resource.
