### ISSUE TITLE
Require images for ARM64

### ISSUE THREAD

**Issue by odidev** [spring-io/artifactory-resource#83]
Hi Team,

I am trying to use the artifactory-resource image on the arm64 platform, but it seems it is not available for arm64 platform. I have built the same in the local arm64 machine, by building jar after skipping tests as I was facing below issues with integration tests:
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 256.561 s <<< FAILURE! - in io.spring.concourse.artifactoryresource.artifactory.ApplicationIT
[ERROR] integrationTest  Time elapsed: 246.539 s  <<< ERROR!
java.lang.RuntimeException:
java.lang.IllegalStateException: The cluster failed to pass a startup check: Encountered an exception: java.lang.IllegalArgumentException: No internal port '8081' for container 'artifactory': Ports [ports=[]]
        at com.palantir.docker.compose.connection.Container.lambda$port$4(Container.java:91)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.palantir.docker.compose.connection.Container.port(Container.java:91)
        at com.palantir.docker.compose.connection.Container.portIsListeningOnHttp(Container.java:58)
        at com.palantir.docker.compose.connection.Container.portIsListeningOnHttpAndCheckStatus2xx(Container.java:49)
        at com.palantir.docker.compose.connection.waiting.HealthChecks.lambda$toRespond2xxOverHttp$1(HealthChecks.java:32)
        at com.palantir.docker.compose.connection.waiting.ClusterHealthCheck.lambda$transformingHealthCheck$2(ClusterHealthCheck.java:42)
        at com.palantir.docker.compose.connection.waiting.ClusterWait.lambda$weHaveSuccess$0(ClusterWait.java:63)
        at org.awaitility.core.CallableCondition$ConditionEvaluationWrapper.eval(CallableCondition.java:99)
        at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:222)
        at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:209)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        at io.spring.concourse.artifactoryresource.artifactory.ApplicationIT.getServer(ApplicationIT.java:139)
        at io.spring.concourse.artifactoryresource.artifactory.ApplicationIT.integrationTest(ApplicationIT.java:74)
Caused by: java.lang.IllegalStateException:

```
Port is available but still getting the same issue.

Image built is using openjdk-1.8.0_192.tar.gz which is downloaded for x64 platform from https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/openjdk-1.8.0_192.tar.gz. There is no available tar file for arm64 platform. We can build image on arm64 platform successfully if openjdk tar file for arm64 is made available in the above link.

Do you have any plans in releasing arm64 images?

It will be very helpful if arm64 images are released. If required, I am happy to help but I would like to know regarding the release process that is being used to release x64 images.

**Comment by philwebb** [comment]
It would certainly be nice to support arm64 images, but we don't have an immediate requirement for them ourselves. The released image is built using [this Dockerfile](https://github.com/spring-io/artifactory-resource/blob/master/Dockerfile) and it's triggered from [this CI task](https://github.com/spring-io/artifactory-resource/blob/8fbd44dfc33ce7322dcbf17415b1cec18c0598d6/ci/tasks/build-artifactory-resource-image.yml).

**Comment by odidev** [comment]
Thanks for the information :).

I have used [this Dockerfile](https://github.com/spring-io/artifactory-resource/blob/master/Dockerfile) only for building and was able to build image after building jar skipping integration tests. I have checked the suggested [CI task](https://github.com/spring-io/artifactory-resource/blob/8fbd44dfc33ce7322dcbf17415b1cec18c0598d6/ci/tasks/build-artifactory-resource-image.yml) and it seems we cannot add arm64 builds in that. 

If you are interested, I can add buildx steps in github actions and we can build the image for both x64 and arm64 from it.

**Comment by philwebb** [comment]
I'm not really keen on migrating any elements of the build to GitHub actions here. It might be better if you fork the project and see if you can get your own arm64 build going there first.

**Comment by odidev** [comment]
I have built the image from my side but I am unable to get [openjdk-1.8.0_192](https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/openjdk-1.8.0_192.tar.gz) tar for arm64 and unable to get the source as well to build it. Can I get any suggestions on making this available for arm64?

**Comment by philwebb** [comment]
Sorry @odidev, I'm afraid I don't have any suggestions and I don't have enough free time to devote to the problem. I'm going to close this one for now and leave the current implementation as x86 only.
