### ISSUE TITLE
Skip get task after put

### ISSUE THREAD

**Issue by oleksandr-shulha-rft** [spring-io/artifactory-resource#87]
I`m trying to push an artifacts to the jFrog, but got an error in get task:

```
selected worker: concourse-workers-worker-1
2021-05-31 11:03:05.492 ERROR 13 --- [           main] o.s.boot.SpringApplication               : Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785) [spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) [spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.4.3.jar!/:2.4.3]
	at io.spring.concourse.artifactoryresource.Application.main(Application.java:40) [classes!/:0.0.14]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [artifactory-resource.jar:0.0.14]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [artifactory-resource.jar:0.0.14]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [artifactory-resource.jar:0.0.14]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [artifactory-resource.jar:0.0.14]
Caused by: org.springframework.web.client.HttpClientErrorException$MethodNotAllowed: 405 Method Not Allowed: [no body]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:117) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:660) ~[spring-web-5.3.4.jar!/:5.3.4]
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryBuildRuns.getDeployedArtifacts(HttpArtifactoryBuildRuns.java:106) ~[classes!/:0.0.14]
	at io.spring.concourse.artifactoryresource.command.InHandler.handle(InHandler.java:80) ~[classes!/:0.0.14]
	at io.spring.concourse.artifactoryresource.command.InCommand.run(InCommand.java:53) ~[classes!/:0.0.14]
	at io.spring.concourse.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:50) ~[classes!/:0.0.14]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.4.3.jar!/:2.4.3]
	... 13 common frames omitted
```
PUT task succeed .

Config:
```
- put: artifactory
        params:
          repo: test
          folder: artifacts
          debug: true
          module_layout: none
          download_artifacts: false
          artifact_set:
            - include:
                - "*.txt"
```

         
 How can i disable get task?

**Comment by philwebb** [comment]
We don't offer a way to disable the `get` task. See https://stackoverflow.com/a/38964300/1526192 for more details on that subject. Do you know that you're getting a `405` response?
