### ISSUE TITLE
Expand retries to cover SocketExceptions

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/artifactory-resource#96]
Communication with https://repo.spring.io continues to be pretty flaky. We should consider expanding retries to cover more failures.

```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785) [spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) [spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.4.3.jar!/:2.4.3]
	at io.spring.concourse.artifactoryresource.Application.main(Application.java:40) [classes!/:0.0.15]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [artifactory-resource.jar:0.0.15]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [artifactory-resource.jar:0.0.15]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [artifactory-resource.jar:0.0.15]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [artifactory-resource.jar:0.0.15]
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error deploying artifact /org/springframework/boot/spring-boot-actuator-autoconfigure/2.5.3-SNAPSHOT/spring-boot-actuator-autoconfigure-2.5.3-SNAPSHOT-sources.jar with checksums [Checksums@372cc0ec sha1 = '6c87fe215720ee9ddb2b637734f26128477b0cdb', md5 = '4b855035e58533380c9c69b345219c01']
	at io.spring.concourse.artifactoryresource.command.OutHandler.deploy(OutHandler.java:261) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.OutHandler.deploy(OutHandler.java:253) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.OutHandler.lambda$deployArtifacts$3(OutHandler.java:243) ~[classes!/:0.0.15]
	at java.util.Map.forEach(Map.java:630) ~[na:1.8.0_292]
	at io.spring.concourse.artifactoryresource.command.OutHandler.deployArtifacts(OutHandler.java:243) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.OutHandler.handle(OutHandler.java:133) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.OutCommand.run(OutCommand.java:53) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:50) ~[classes!/:0.0.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.4.3.jar!/:2.4.3]
	... 13 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error deploying artifact /org/springframework/boot/spring-boot-actuator-autoconfigure/2.5.3-SNAPSHOT/spring-boot-actuator-autoconfigure-2.5.3-SNAPSHOT-sources.jar with checksums [Checksums@372cc0ec sha1 = '6c87fe215720ee9ddb2b637734f26128477b0cdb', md5 = '4b855035e58533380c9c69b345219c01']
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_292]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[na:1.8.0_292]
	at io.spring.concourse.artifactoryresource.command.OutHandler.deploy(OutHandler.java:258) ~[classes!/:0.0.15]
	... 21 common frames omitted
Caused by: java.lang.RuntimeException: Error deploying artifact /org/springframework/boot/spring-boot-actuator-autoconfigure/2.5.3-SNAPSHOT/spring-boot-actuator-autoconfigure-2.5.3-SNAPSHOT-sources.jar with checksums [Checksums@372cc0ec sha1 = '6c87fe215720ee9ddb2b637734f26128477b0cdb', md5 = '4b855035e58533380c9c69b345219c01']
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryRepository.deploy(HttpArtifactoryRepository.java:91) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.OutHandler.deployArtifact(OutHandler.java:277) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.OutHandler.lambda$getArtifactDeployer$5(OutHandler.java:270) ~[classes!/:0.0.15]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[na:1.8.0_292]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[na:1.8.0_292]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_292]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_292]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_292]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[na:1.8.0_292]
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on PUT request for "https://repo.spring.io/libs-snapshot-local/org/springframework/boot/spring-boot-actuator-autoconfigure/2.5.3-SNAPSHOT/spring-boot-actuator-autoconfigure-2.5.3-SNAPSHOT-sources.jar;build.name=spring-boot;build.number=spring-boot-2.5.x-build-919;build.timestamp=1626940647415": Connection reset; nested exception is javax.net.ssl.SSLException: Connection reset
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:660) ~[spring-web-5.3.4.jar!/:5.3.4]
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryRepository.deployUsingContent(HttpArtifactoryRepository.java:107) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryRepository.deploy(HttpArtifactoryRepository.java:79) ~[classes!/:0.0.15]
	... 8 common frames omitted
Caused by: javax.net.ssl.SSLException: Connection reset
	at sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[na:1.8.0_292]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324) ~[na:1.8.0_292]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[na:1.8.0_292]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1554) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketImpl.access$400(SSLSocketImpl.java:73) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:964) ~[na:1.8.0_292]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_292]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_292]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_292]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735) ~[na:1.8.0_292]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[na:1.8.0_292]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593) ~[na:1.8.0_292]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[na:1.8.0_292]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_292]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352) ~[na:1.8.0_292]
	at org.springframework.http.client.SimpleClientHttpResponse.getRawStatusCode(SimpleClientHttpResponse.java:55) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.DefaultResponseErrorHandler.hasError(DefaultResponseErrorHandler.java:64) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:807) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777) ~[spring-web-5.3.4.jar!/:5.3.4]
	... 11 common frames omitted
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_292]
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[na:1.8.0_292]
		at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[na:1.8.0_292]
		at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81) ~[na:1.8.0_292]
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:355) ~[na:1.8.0_292]
		... 29 common frames omitted
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[na:1.8.0_292]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:457) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1332) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:948) ~[na:1.8.0_292]
	... 24 common frames omitted
```

```

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785) [spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) [spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.4.3.jar!/:2.4.3]
	at io.spring.concourse.artifactoryresource.Application.main(Application.java:40) [classes!/:0.0.15]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [artifactory-resource.jar:0.0.15]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [artifactory-resource.jar:0.0.15]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [artifactory-resource.jar:0.0.15]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [artifactory-resource.jar:0.0.15]
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error deploying artifact /org/springframework/boot/spring-boot-starter-thymeleaf/2.6.0-SNAPSHOT/spring-boot-starter-thymeleaf-2.6.0-SNAPSHOT.pom with checksums [Checksums@4069123f sha1 = '160ae3288f331132b62caf3ee2b37272e14a7707', md5 = '3b91fecd1f1eb594288c3ced42d91cfa']
	at io.spring.concourse.artifactoryresource.command.OutHandler.deploy(OutHandler.java:261) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.OutHandler.deploy(OutHandler.java:253) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.OutHandler.lambda$deployArtifacts$3(OutHandler.java:243) ~[classes!/:0.0.15]
	at java.util.Map.forEach(Map.java:630) ~[na:1.8.0_292]
	at io.spring.concourse.artifactoryresource.command.OutHandler.deployArtifacts(OutHandler.java:243) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.OutHandler.handle(OutHandler.java:133) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.OutCommand.run(OutCommand.java:53) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:50) ~[classes!/:0.0.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.4.3.jar!/:2.4.3]
	... 13 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error deploying artifact /org/springframework/boot/spring-boot-starter-thymeleaf/2.6.0-SNAPSHOT/spring-boot-starter-thymeleaf-2.6.0-SNAPSHOT.pom with checksums [Checksums@4069123f sha1 = '160ae3288f331132b62caf3ee2b37272e14a7707', md5 = '3b91fecd1f1eb594288c3ced42d91cfa']
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_292]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[na:1.8.0_292]
	at io.spring.concourse.artifactoryresource.command.OutHandler.deploy(OutHandler.java:258) ~[classes!/:0.0.15]
	... 21 common frames omitted
Caused by: java.lang.RuntimeException: Error deploying artifact /org/springframework/boot/spring-boot-starter-thymeleaf/2.6.0-SNAPSHOT/spring-boot-starter-thymeleaf-2.6.0-SNAPSHOT.pom with checksums [Checksums@4069123f sha1 = '160ae3288f331132b62caf3ee2b37272e14a7707', md5 = '3b91fecd1f1eb594288c3ced42d91cfa']
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryRepository.deploy(HttpArtifactoryRepository.java:91) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.OutHandler.deployArtifact(OutHandler.java:277) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.command.OutHandler.lambda$getArtifactDeployer$5(OutHandler.java:270) ~[classes!/:0.0.15]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[na:1.8.0_292]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[na:1.8.0_292]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_292]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_292]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_292]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[na:1.8.0_292]
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on PUT request for "https://repo.spring.io/libs-snapshot-local/org/springframework/boot/spring-boot-starter-thymeleaf/2.6.0-SNAPSHOT/spring-boot-starter-thymeleaf-2.6.0-SNAPSHOT.pom;build.name=spring-boot;build.number=spring-boot-2.6.x-build-182;build.timestamp=1626940743975": Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:660) ~[spring-web-5.3.4.jar!/:5.3.4]
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryRepository.deployUsingContent(HttpArtifactoryRepository.java:107) ~[classes!/:0.0.15]
	at io.spring.concourse.artifactoryresource.artifactory.HttpArtifactoryRepository.deploy(HttpArtifactoryRepository.java:79) ~[classes!/:0.0.15]
	... 8 common frames omitted
Caused by: java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851) ~[na:1.8.0_292]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[na:1.8.0_292]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593) ~[na:1.8.0_292]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[na:1.8.0_292]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_292]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352) ~[na:1.8.0_292]
	at org.springframework.http.client.SimpleClientHttpResponse.getRawStatusCode(SimpleClientHttpResponse.java:55) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.DefaultResponseErrorHandler.hasError(DefaultResponseErrorHandler.java:64) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:807) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777) ~[spring-web-5.3.4.jar!/:5.3.4]
	... 11 common frames omitted
```

I'm not sure how easy this will be. It's not clear from the failures what state the server will be in. Retrying, particularly in the " Unexpected end of file from server" case, may result in another failure as the server already has the artifact that we're trying to upload.

**Comment by wilkinsona** [comment]
In the connection reset case it would appear that the deployment fails and the artifact is not upload. It looks like it would be safe to retry.

In the unexpected end of file from server case it would appear that the deployment has succeeded. Unfortunately, Artifactory's documentation doesn't say what will happen if an artifact is uploaded twice so it's not clear if we need to check if the artifact is there before retrying.
